instagram/config/routes.rb
Rails.application.routes.draw do
  
  get 'bookmarks/create'
  get 'bookmarks/destroy'
  # we got these two routes from using rails g controller
  # get 'posts/index'
  # get 'users/show'
  
  # we made our pages controller's home action's view as our default home page(root)
  root 'posts#index'
  
  # we did this to change the names of links in the url
  devise_for :users,
   path: '',
   path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
   controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  # get '/users/:id', to: 'users#show'
  # /users/3 -> Users controller, show action, params {id: '3'}
   resources :users, only: [:index, :show]

   # resources doesn't needs us to send id in the url as well, so it is same as get '/posts/:id', to: 'posts#show'.
   # Also, we have used nested resoures for photos as it's like a child of post. Everytime we will need a post_id when we need a photo!
  resources :posts, only: [:index, :show, :create, :destroy] do
    resources :photos, only: [:create]
    resources :likes, only: [:create,  :destroy], shallow: true
    resources :comments, only: [:index, :create, :destroy], shallow: true
    resources :bookmarks, only: [:create, :destroy], shallow: true 
  end

end

instagram/app/views/shared/_devise-messages.html.erb
<% if resource.errors.any? %>
	<script type="text/javascript">
		<% resource.errors.full_messages.each do |value| %>
		toastr.error('<%= value %>')
         <% end %>
	</script>
<% end %>

instagram/app/views/shared/_footer.html.erb
<footer>
	

        	<div class="row">
        		<a href="" class="col nav-item nav-link" href="#">ABOUT US</a>
        		<a href="" class="col nav-item nav-link" href="#">SUPPORT</a>
        		<a href="" class="col nav-item nav-link" href="#">API</a>
        		<a href="" class="col nav-item nav-link" href="#">JOBS</a>
        		<a href="" class="col nav-item nav-link" href="#">PRIVACY</a>
        		<a href="" class="col nav-item nav-link" href="#">PROFILES</a>
        		<a href="" class="col nav-item nav-link" href="#">HASHTAGS</a>
        		<a href="" class="col nav-item nav-link" href="#">LANGUAGES</a>

        		<!-- <div style="color:#999; font-weight: 600;font-size: 12px;line-height: 18px;">&copy; 2018 INSTAGRAM</div> -->
        	</div>
	
</footer>

instagram/app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
            <a class="navbar-brand core-sprite hide-text" href="<%= root_path%>">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            

            <!-- FORM FOR SEARCH -->
            
            <!-- form_for creates a form for an object of a model, while form_tag simply creates a form (in general, used for search) -->
            <!-- users path takes to index action of users_controller -->

            <%= form_tag users_path, method: :get, class: "form-inline my-2 my-lg-0 ml-md-auto", id: "users-search", remote: true do %>
              <%= text_field_tag :term, params[:term], class: "form-control mr-sm-2 text-center common-btn", placeholder: "Search", autocomplete: "off" %>
              <div id="users-result"></div> <!-- This is the dropdown which shows users found for given search query. Here, results will come from index.js.erb file from AJAX -->
            <% end %>


            <ul class="navbar-nav ml-md-auto">
              <li class="nav-item">
                <a class="nav-link core-sprite explore-icon hide-text" href="#">Explore</a>
              </li>
              <li class="nav-item">
                <a class="nav-link  core-sprite notification-icon hide-text" href="#">Notification</a>
              </li>
              <li class="nav-item">
                <%= link_to "Profile", user_path(current_user), class: "nav-link core-sprite profile-icon hide-text"%>
              </li>
              
            </ul>
            
            </div>
        </div>
    </nav>