instagram/config/routes.rb
Rails.application.routes.draw do
  
  get 'bookmarks/create'
  get 'bookmarks/destroy'
  # we got these two routes from using rails g controller
  # get 'posts/index'
  # get 'users/show'
  
  # we made our pages controller's home action's view as our default home page(root)
  root 'posts#index'
  
  # we did this to change the names of links in the url
  devise_for :users,
   path: '',
   path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
   controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  # get '/users/:id', to: 'users#show'
  # /users/3 -> Users controller, show action, params {id: '3'}
   resources :users, only: [:index, :show]

   # resources doesn't needs us to send id in the url as well, so it is same as get '/posts/:id', to: 'posts#show'.
   # Also, we have used nested resoures for photos as it's like a child of post. Everytime we will need a post_id when we need a photo!
  resources :posts, only: [:index, :show, :create, :destroy] do
    resources :photos, only: [:create]
    resources :likes, only: [:create,  :destroy], shallow: true
    resources :comments, only: [:index, :create, :destroy], shallow: true
    resources :bookmarks, only: [:create, :destroy], shallow: true 
  end

end

instagram/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :likes, -> {order(:created_at => :desc)}
  has_many :comments, -> {order(:created_at => :desc)}
  has_many :bookmarks




# this method take a variable/argument 'user' which comes/is passed from the view and returns true or false depending upon if the current signed-in user is the owner of the post
  def is_belongs_to? user
  	Post.find_by(user_id: user.id, id: id)
  	# Post.find_by(user_id: user.id, id: self.id) both are same, it's just that self is not required, rails is smart!
  end

# method to check if current post has been liked by current signed-in user or not, returns like_id 
  def is_liked user
  	Like.find_by(user_id: user_id, post_id: id)
  end

# bookmark is same as like feature
  def is_bookmarked user
    Bookmark.find_by(user_id: user_id, post_id: id)
  end
  
end

instagram/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  

  before_action :authenticate_user!
  before_action :find_post, only: [:show, :destroy]


  # includes is like a join table between posts and photos/user/likes
  def index
  	# @posts = Post.all.limit(10).includes(:photos, :user, :likes).order('created_at desc')

    @posts = Post.paginate(:page => params[:page], :per_page => 5).includes(:photos, :user, :likes).order('created_at desc')
  	@post = Post.new
  end


# build creates a new record with current user's id 
  def create
  	@post = current_user.posts.build(post_params)
  	if @post.save
  		if params[:images]
  			params[:images].each do |img|
  				@post.photos.create(image: img[1])
          # img  is a hash, and img[1]   will return image object.
  			end
  		end
  		redirect_to posts_path
  		flash[:notice] = "New post added ..."
  	else
  		flash[:alert] = "Something went wrong ..."
  		redirect_to posts_path
  	end
  end

# show method is for showing a particular post
  def show
    @photos = @post.photos
    @likes = @post.likes.includes(:user)
    @bookmarks = @post.bookmarks.includes(:user)
    @comment = Comment.new
    @is_liked = @post.is_liked(current_user)
    @is_bookmarked = @post.is_bookmarked(current_user)
  end

# for deleting a post
  def destroy
  # check signed in user is the creator of post
    if @post.user == current_user 
      if @post.destroy
        flash[:notice] = "Post deleted!"
      else
        flash[:alert] = "Something went wrong ..."
      end
    else
      flash[:notice] = "You don't have permission to do that!"
    end
    redirect_to root_path
  end

  private
  def find_post
  	@post = Post.find_by id: params[:id]

# returns to the method which called find_post, if a post is found. Else, flashes danger. Finally redirects to root
  	return if @post
  	flash[:danger] = "Post not found!"
  	redirect_to root_path	
  end

# post_params method uses STRONG PARAMS which has 'require' and 'permit' to make sure we can't create or edit posts by changing data from opening chrome developer tools only! Only the content is visible from that side, not the post_id
  def post_params
  	params.require(:post).permit :content
  end

end

instagram/app/helpers/posts_helper.rb
module PostsHelper
end

instagram/app/views/posts/_bookmark_icon.html.erb
<!-- if the post is already bookmarked, it will act as a destroy button. On clicking this link, bookmark will be deleted -->
<% if is_bookmarked.present? %>
	<%= link_to "Bookmarked", bookmark_path(is_bookmarked), method: :delete, remote: true, class: "core-sprite bookmarked hide-text" %>
<!--  else we will show the bookmark icon so that user can send a post request  -->
<% else %>
	<%= link_to "Bookmark", post_bookmarks_path(post), method: :post, remote: true, class: "core-sprite bookmark hide-text" %>
<% end %>

instagram/app/views/posts/_comment_form.html.erb
<!-- [@post, Comment.new] means form_for will generate a post_id before we generate a new comment -->
<%= form_for [post, Comment.new], :html => {:class => "w-100"}, remote: true do |f| %>
	<%= f.hidden_field :user_id, value: current_user.id %>
	<%= f.hidden_field :post_id, value: post.id %>
	<%= f.text_field :content, class: "form-control comment-input border-0", placeholder: "Add a comment ...", autocomplete: :off %>
<% end %>

instagram/app/views/posts/_comment_list.html.erb
<% post.comments.each do |comment|  %>
  <div class="mb-2">
    <% if comment.user == current_user %>
      <%= link_to "Delete Comment", comment_path(comment), method: :delete, remote: true, class: "core-sprite delete-comment hide-text"%>
    <% end %>
    <span>
    	<strong>
    		<%= link_to comment.user.name, user_path(comment.user), class: "no-text-decoration normal-color" %>
    	</strong>
    </span>
    <span><%= comment.content %></span>
  </div>
<% end %>

instagram/app/views/posts/_like_icon.html.erb
<% if is_liked.present? %>
  <%= link_to "Love", like_path(is_liked), method: :delete, remote: true,
    class: "core-sprite loved hide-text" %>
<% else %>
  <%= link_to "Loved", post_likes_path(post), method: :post, remote: true,
    class: "core-sprite love hide-text" %>
<% end %>

instagram/app/views/posts/_like_text.html.erb
<% likes.each.with_index do |like, index| %>
<strong>
  <% if likes.size == 1 %>
    <%= like.user.name %> </strong> likes this
  <% elsif like == likes.last %>
    </strong>and<strong>
    <%= + like.user.name %></strong> like this
  <% elsif index > 1 %>
    </strong><%= "and" +(likes.size-index).to_s + " others" %> like this
    <% break %>
  <% elsif index==likes.size-2 || index == 1 %>
    <%= like.user.name %>
  <% else %>
    <%= like.user.name + ", " %>
  <% end %>
<% end %>

instagram/app/views/posts/_photos.html.erb
<%= link_to post_path(post) do %>

<% if post.photos.size == 1 %>
  <%= image_tag post.photos.first.image.url(:standard), class: "card-img-top" %>
<% else %>
  <div class="carousel slide" data-ride="carousel" id="carousel-post-<%= @post.id %>">
    <div class="carousel-inner">
      <% post.photos.each do |photo| %>
        <% if photo == post.photos.first %>
          <div class="carousel-item active">
        <% else %>
          <div class="carousel-item">
        <% end %>
            <%= image_tag photo.image.url(:standard), class: "card-img-top" %>
          </div>
      <% end %>
    </div>
    <a class="carousel-control-prev" href="#carousel-post-<%= @post.id %>" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-post-<%= @post.id %>" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
<% end %>

<% end %>

instagram/app/views/posts/_posts_list.html.erb
<!-- standard is the version that we can define the way we want (uploaders->photo_uploader.rb) -->

<% @posts.each do |post| %>

	<div class="card mt-3 post">
		
    <!-- username/user avatar/delete options -->	
		<div class="card-header d-flex align-items-center">
			<%=  link_to user_path(post.user), class: "no-text-decoration" do %>
				<%= image_tag avatar_url(post.user), class: "post-author-icon" %>
			<% end %>

			<%= link_to user_path(post.user), class: "normal-color no-text-decoration", title: post.user.name do%>
				<strong><%= post.user.name %></strong>
			<% end %>
    <!-- show the delete post icon only when signed in user is the owner of the post. is_belongs_to is a method defined in post.rb model file -->
			<% if post.is_belongs_to? current_user %>
		        <%= link_to post_path(post), method: :delete, class: "ml-auto delete-post-icon mx-0 my-auto" do %>
		          <i class="far fa-trash-alt" aria-hidden="true"></i>
		        <% end %>
	      	<% end %>
		</div>


<!----------------------- DISPLAY PHOTOS USING BOOTSTRAP MODAL------to stop auto-slide: data-interval="false"---------------------------------------- -->
<%= render "photos", {post: post}%>


<!------------------------------------------------------LIKE/COMMENT/BOOKMARK----------------------------------------------------------------- -->

	<div class="card-body">
		
		<div class="row-actions" style="display: flex; margin-top: 3%;margin-bottom: 3%;">
          
          <!-- LIKE ICON -->
          <!--change the icon of love react from red to normal if a like_id already exists and vice-versa! We are passing the required data in params, {}, to the file which is rendered here-->
            <div id="like-icon-post-<%= post.id.to_s %>">
          		<%= render "like_icon", {is_liked: post.is_liked(current_user), post: post} %>
            </div>

            <!-- COMMENT ICON --> 
			<a href="#", class="core-sprite comment hide-text">Comment</a>

			<!-- BOOKMARK ICON -->
	        <div id="bookmark-icon-post-<%= post.id.to_s %>" class="ml-auto">
          		<%= render "bookmark_icon", {is_bookmarked: post.is_bookmarked(current_user), post: post} %>
        	</div>

		</div>

		<!-- LIKE TEXT LOGIC -->
		<!-- styling the text of likes' length and users who like it! We are passing post.likes as likes, in params to the file which is rendered here -->
		<div id="like-text-post-<%= post.id.to_s %>">
        	<%= render "like_text", {likes: post.likes} %>
        </div>
		
		<!-- COMMENTS LIST -->
		<div>
			<span><strong><%= post.user.name %></strong></span>
			<span><%= post.content %></span>
		</div>
		<div id="comment-post-<%= @post.id.to_s %>">
        	<%= render "comment_list", {post: post} %>
      	</div>

		<%= link_to time_ago_in_words(post.created_at).upcase + " AGO ", post_path(post), class: "light-color post-time no-text-decoration"%>
		<hr>

		<!-- COMMENT FORM -->
		<div class="row actions" id="comment-form-post-<%= post.id.to_s %>">
			<%= render "comment_form", {post: post} %>
		</div>
	
	</div>

</div>

<% end %>

instagram/app/views/posts/index.html.erb
<!-- rails' form for helper writes HTML code for us! Here, on pressing submit button, routes will send the request to posts controller which will see what needs to be done ahead -->


<!-- STYLING THE POST FORM -->

<div class="d-flex flex-column align-items-center mt-3">
	<div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
		<div class="card">
			<div class="card-header">
				Create Post			
			</div>
			<div class="card-body">
				<%= form_for @post, :html => {:multipart => true, :class => "dropzone upload-images p-0 border-0"} do |f| %>
					<div class="form-group row mt-2">
						<div class="col-auto pr-0">
							<%= image_tag avatar_url(current_user), class: "post-author-icon" %>
						</div>
						<div class="col pl-0">
							<%= f.text_field :content, class: "form-control border-0", placeholder: "Say something about this..." %>
						</div>
					</div>


<!-- If you want another name than file you can configure dropzone with the option paramName.

If you want your file uploads to work even without JavaScript, you can include an element with the class fallback that dropzone will remove if the browser is supported. If the browser isn’t supported, Dropzone will not create fallback elements if there is a fallback element already provided. (Obviously, if the browser doesn’t support JavaScript, the form will stay as is)

Typically this will look like this:

<form action="/file-upload" class="dropzone">
  <div class="fallback">
    <input name="file" type="file" multiple />
  </div>
</form> -->

		<div class="fallback">
			<%= file_field_tag "images[]", type: :file, multiple: true %>
		</div>
		<div class="dz-message m-0"></div>
			<div class="dropzone-previews mb-3">
				<div class="upload-photos-icon">
					<i class="fa fa-plus fa-2x" aria-hidden="true" style="color: #dddfe2"></i>
				</div>
			</div>
		<%= f.submit "Post", class: "btn btn-primary" %>
	<% end %>
</div>
		</div>

		<div id="posts">
			<%= render 'posts/posts_list' %>
		</div>


	</div>

	<!-- will paginate gem used -->
	<br>
	<%= will_paginate @posts %>
</div>

instagram/app/views/posts/show.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="row post box col-xl-10 col-lg-11 col-xs-12">
    <div class="col-lg-8 col-md-7 px-0 d-flex post-show-img">
      <div class="align-self-center">
        <%= render "photos", {post: @post} %>
      </div>
    </div>
    <div class="col-lg-4 col-md-5 mt-sm-4 mt-md-0">
      <div class="row px-3 d-flex align-items-center">
        <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
          <%= image_tag avatar_url(@post.user), class: "post-author-icon" %>
        <% end %>
        <%= link_to user_path(@post.user), class: "normal-color no-text-decoration d-flex align-self-center",
          title: @post.user.name do %>
          <strong><%= @post.user.name %></strong>
        <% end %>
        <% if @post.is_belongs_to? current_user %>
          <%= link_to post_path(@post), method: :delete, class: "ml-auto delete-post-icon mx-0 my-auto" do %>
            <i class="far fa-trash-alt" aria-hidden="true"></i>
          <% end %>
        <% end %>
      </div>
      <hr class="mb-0">
      <div class="comment-list py-2">
      <% if @post.content.present? %>
        <div>
          <span><strong><%= @post.user.name %></strong></span>
          <span><%= @post.content %></span>
        </div>
      <% end %>
      
      <!--COMMENTS LIST -->
      <div id="comment-post-<%= @post.id.to_s %>">
        <%= render "comment_list", {post: @post} %>
      </div>
      
      </div>
      <hr class="mt-0">

      <div class="row actions">
        
        <!-- LIKE ICON -->
        <div id="like-icon-post-<%= @post.id.to_s %>">
          <%= render "like_icon", {is_liked: @is_liked, post: @post} %>
        </div>

        <!-- COMMENT ICON -->
        <a href="#" class="core-sprite comment hide-text">Comment</a>
        
        <!-- BOOKMARK ICON -->
        <div id="bookmark-icon-post-<%= @post.id.to_s %>" class="ml-auto">
          <%= render "bookmark_icon", {is_bookmarked: @is_bookmarked, post: @post} %>
        </div>

      </div>

      <!-- LIKE TEXT LOGIC-->
      <div id="like-text-post-<%= @post.id.to_s %>">
        <%= render "like_text", {likes: @likes} %>
      </div>
      
      <div class="light-color post-time"><%= time_ago_in_words(@post.created_at).upcase %> AGO</div>
      <hr>
      
      <!--  COMMENT FORM -->
      <div class="row actions">
        <div class="row actions" id="comment-form-post-<%= @post.id.to_s %>">
          <%= render "comment_form", {post: @post} %>
        </div>
      </div>

    
    </div>
  </div>
</div>